Repository krestomatio/container_builder, pull requests merged in 2021-11, with the labels that each got.

#75 refactor(moodle_web): adjust config.php permissions
  .ansible-ci/files/templated_contexts/moodle_php-fpm/conf/container-entrypoint.d/php-moodle-entrypoint
  .ansible-ci/inventory/host_vars/go-toolset/dockerfile_builder.yml
Labels: size/XS

#76 chore(ansible-operator-ci): bump operator
  .ansible-ci/inventory/host_vars/ansible-operator-ci/dockerfile_builder.yml
Labels: approved

#77 Remove install - deprecated and remove open-vm-tools
  .ansible-ci/files/templated_contexts/rocky8-minimal/rocky8-minimal.ks
Labels: lgtm, size/XS, approved, ok-to-test
